name: audiotags
description: Read and write audio metadata in Flutter. Supports multiple formats.
version: 1.4.5
publish_to: none
homepage: https://github.com/erikas-taroza/audiotags
repository: https://github.com/erikas-taroza/audiotags

platforms:
  android:

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  ffi: ^2.1.3
  flutter_rust_bridge: 2.11.1
  meta: ^1.15.0
  uuid: ^4.5.1
  freezed_annotation: ^3.0.0
  # Needed to run codegen. Uncomment to run codegen, otherwise keep it commented so the package can be published.
  # rust_lib_audiotags:
  #   path: rust_builder

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  ffigen: ^16.1.0
  build_runner: ^2.4.15
  freezed: ^2.5.8
  analyzer: ^7.3.0

flutter:
  plugin:
    platforms:
      android:
        package: com.erikas.audiotags
        pluginClass: AudiotagsPlugin
