[package]
name = "audiotags"
version = "1.4.5"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
flutter_rust_bridge = "=2.11.1"
lofty = "0.21.0"
anyhow = "1.0.89"

[profile.release]
lto = true
